# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT
# Mod Properties
mod_version=1.2.2
maven_group=org.lolicode
archives_base_name=NekoMusic_Server-fabric-1.21.9
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.134.0+1.21.9
carpet_branch=1.21.9
carpet_core_version=1.4.185+v250930
fabric_language_kotlin_version=1.13.6+kotlin.2.2.20
badpackets_version=0.10.1
fabric_permissions_api_version=0.4.0
# Non-mod dependencies
okhttp_version=4.12.0
okio_version=3.16.0
qr_to_console_version=1.0
zxing_javase_version=3.5.3
zxing_core_version=3.5.3
